import type { NextConfig } from "next";

// PWA is currently disabled because the directory path "Jackie's Boneyard Archive"
// contains a single quote, which breaks the autogenerated service worker code
// from next-pwa/workbox. The site remains installable via manifest.json.

const nextConfig: NextConfig = {
  async redirects() {
    return [
      {
        source: "/services",
        destination: "/solutions",
        permanent: true,
      },
      {
        source: "/about",
        destination: "/story",
        permanent: true,
      },
    ];
  },
};

export default nextConfig;
