"use client";

import { Container } from "@/components/ui/Container";
import { Footer } from "@/components/layout/Footer";
import { motion } from "framer-motion";

export default function LicensePage() {
    return (
        <div className="bg-brand-black min-h-screen">
            <section className="relative pt-32 pb-20 md:pt-48 md:pb-32">
                <Container>
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.8 }}
                        className="max-w-3xl"
                    >
                        <h1 className="font-display font-medium text-5xl md:text-7xl leading-[0.9] tracking-tighter text-brand-white mb-8">
                            LICENSE<br />
                            <span className="text-brand-text-muted">AGREEMENT.</span>
                        </h1>

                        <div className="space-y-8 text-brand-text-muted font-sans text-lg leading-relaxed">
                            <p>
                                This agreement governs the use of Polk Systems software and hardware deployed in your property. By engaging Polk Systems for installation, you agree to the following terms.
                            </p>

                            <div className="border-t border-white/10 pt-8">
                                <h2 className="font-display text-2xl text-brand-white mb-4">Software License</h2>
                                <p>
                                    Polk Systems grants you a non-exclusive, non-transferable license to operate the Polk Core software on hardware installed at your property. The software is licensed, not sold. Updates are delivered locally and applied at your discretion.
                                </p>
                            </div>

                            <div className="border-t border-white/10 pt-8">
                                <h2 className="font-display text-2xl text-brand-white mb-4">Data Ownership</h2>
                                <p>
                                    All data generated by your Polk System — including sensor logs, behavioral patterns, and security recordings — is your property. Polk Systems has no access to this data. You may export, delete, or archive your data at any time through the local admin interface.
                                </p>
                            </div>

                            <div className="border-t border-white/10 pt-8">
                                <h2 className="font-display text-2xl text-brand-white mb-4">Restrictions</h2>
                                <p>
                                    You may not reverse-engineer, decompile, or distribute the Polk Core software. Modifications to hardware must be performed by authorized Polk Systems technicians to maintain warranty coverage.
                                </p>
                            </div>

                            <div className="border-t border-white/10 pt-8">
                                <h2 className="font-display text-2xl text-brand-white mb-4">Contact</h2>
                                <p>
                                    For licensing inquiries, reach us at{" "}
                                    <a href="mailto:hello@polksystems.com" className="text-brand-accent hover:underline">
                                        hello@polksystems.com
                                    </a>.
                                </p>
                            </div>

                            <p className="text-sm text-brand-text-muted/60 pt-8 border-t border-white/10">
                                Last updated: February 2026
                            </p>
                        </div>
                    </motion.div>
                </Container>
            </section>

            <Footer />
        </div>
    );
}
